### ISSUE TITLE
不会正确地获得RPC服务器地址。

### ISSUE THREAD

**Issue by giveup** [aa65535/yaaw-zh-hans#2]
例如192.168.1.1/yaaw，会提示RPC服务器错误，需要手动设置。默认的是http://localhost:6800/jsonrpc
原版的yaaw是会自动获得正确的RPC服务器。例如192.168.2.1/yaaw，
RPC则会变成http://192.168.2.1:6800/jsonrpc

**Comment by aa65535** [comment]
填写的时候需要自己指定正确的协议。

**Comment by giveup** [comment]
我知道要填写正确的地址，我的意思是原版yaaw能自动填写正确的RPC地址，这个fork不能修一下吗？

**Comment by aa65535** [comment]
所谓的自动获取RPC地址就是根据当前 yaaw 访问地址进行的生成的。
```js
this.jsonrpc_path = $.Storage.get("jsonrpc_path") || location.protocol+"//"+(location.host.split(":")[0]||"localhost")+":6800"+"/jsonrpc";
```
但是 yaaw 和 aria2 并不一定在同一地址下。
