### ISSUE TITLE
https页面中的设置问题

### ISSUE THREAD

**Issue by BURN1NGDES1RE** [aa65535/yaaw-zh-hans#5]
求助
在http://aria2c.com/ 页面中设置JSON-RPC PATH: http://token:TOKEN@localhost:6800/jsonrpc
可以成功显示正在下载的任务

但在https://aria2c.com/ 页面中将JSON-RPC PATH同样设置为 http://token:TOKEN@localhost:6800/jsonrpc
显示Aria2 RPC 服务器错误
改为 https://token:TOKEN@localhost:6800/jsonrpc 也不成功

**Comment by aa65535** [comment]
在 https://aria2c.com/ 下需要将 JSON-RPC PATH 设置为 https 或者 wss 协议，支持此协议需要有证书的支持，如果没用域名和对应的证书的话建议继续使用 http://aria2c.com/ .
