### ISSUE TITLE
[question] Does aria2c.com support private rpc address?

### ISSUE THREAD

**Issue by ghost** [aa65535/yaaw-zh-hans#7]
Hi,

So by far in my test. The aria2c.com only support localhost:6800 in the JSON-RPC Path field.
(example: http://token:xxx@localhost:6800/jsonrpc)
It keep showing RPC error if using private ip address. Even if other software such as AriaNG/yaaw get connected with same setting. 
(example: http://token:xxx@192.168.1.1:6800/jsonrpc)

Port connection ability verified with ?jsoncallback=1.
The respond: 1({"id":null,"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid Request."}})

Does aria2c.com support private rpc address?

**Comment by aa65535** [comment]
Use http://aria2c.com/ instead of https://aria2c.com/

Detailed information can be found in the console log.

**Comment by zoglun** [comment]
Cool,
Please close this issues as resolved.
Thank you.
